Add pymc support to predictive explorer
arviz-devs/preliz pull request #450
Opened 2024-06-01 13:25 UTC by rohanbabbar04

## Description
 - Add pymc support to predictive_explorer.
 - Add parameter `engine` to predictive_explorer.
 - Add test in test_predictive_explorer.py.
- Update docs

## Checklist

- [x] Code style is correct (follows pylint and black guidelines)
- [x] Includes new or updated tests to cover the new feature
- [x] New features are properly documented (with an example if appropriate)
- [x] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [x] Widget states have been properly saved (only for notebooks with widgets) [see](https://github.com/arviz-devs/preliz/wiki/Save-widgets-state) for details.

2024-06-01 19:08 UTC, aloctavodia requested changes

2024-06-01 19:08 UTC, aloctavodia commented on preliz/internal/plot_helper.py
> +        reshaped_t = np.reshape(results.T, (-1, results.shape[0]))
```suggestion

```

2024-06-01 19:08 UTC, aloctavodia commented on preliz/internal/plot_helper.py
> +            reshaped_t,
```suggestion
            results,
```

2024-06-01 19:12 UTC, aloctavodia commented
sample_prior_predictive emits a message. saying "Samplig", plus a list of the sampled variables. We should disable that message. It is generated with the logging module. We should suppress it locally with a context manager, or disable it before sampling and enable it again after sampling. We need to do this to avoid messing up calls to `sample_prior_predictive` outside of predictive_explorer

2024-06-01 19:24 UTC, aloctavodia commented
It is no needed for this PR, but to think about it we may want to try to guess the value of "engine", for instance for a pymc model we could inspect the source and detect the regex pattern for "with pm.Model() as" where the particle "pm." is something that can vary.

We may want to keep the "engine" argument and default to "auto" or something similar, just in case our automatic detection fails

2024-06-02 07:56 UTC, rohanbabbar04 commented on preliz/internal/plot_helper.py
> +        results = np.array(results)
Got it 
Thanks...

2024-06-02 07:57 UTC, rohanbabbar04 commented
> sample_prior_predictive emits a message. saying "Samplig", plus a list of the sampled variables. We should disable that message. It is generated with the logging module. We should suppress it locally with a context manager, or disable it before sampling and enable it again after sampling. We need to do this to avoid messing up calls to `sample_prior_predictive` outside of predictive_explorer

Created a contextmanager to handle the logs generated during this step.

2024-06-02 07:57 UTC, rohanbabbar04 commented
> It is not needed for this PR, but something to think about.
> 
> We may want to try to guess the value of "engine", for instance for a pymc model we could inspect the source and detect the regex pattern for "with pm.Model() as" where the particle "pm." is something that can vary. For Bambi it should also be simple to detect it.
> 
> We may want to keep the "engine" argument and default to "auto" or something similar, just in case our automatic detection fails

Sounds good.... Let me create a new issue for this

2024-06-02 08:00 UTC, rohanbabbar04 commented
I am currently keeping the sampling pymc code separated from the preliz code, like it was discussed in the jupyter notebook.
Better to not disrupt the current implementation of the already existing preliz code.

2024-06-03 16:49 UTC, aloctavodia commented
agreed, we can refactor and combine later

2024-06-03 16:51 UTC, merged

2024-06-03 17:14 UTC, rohanbabbar04 commented
> agreed, we can refactor and combine later. Something really easy to combine is the plotting part, right?

Yes...